import { Category } from "@/types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Tarot",
    icon: "cards-outline",
    iconSet: "MaterialCommunityIcons",
    subcategories: ["Lettura generale", "Amore", "Carriera"],
  },
  {
    id: "2",
    name: "Astrology",
    icon: "planet-outline",
    iconSet: "Ionicons",
    subcategories: ["Tema natale", "Previsioni"],
  },
  {
    id: "3",
    name: "Quantum Healing",
    icon: "sparkles-outline",
    iconSet: "Ionicons",
    subcategories: [],
  },
  {
    id: "4",
    name: "Yoga",
    icon: "yoga",
    iconSet: "MaterialCommunityIcons",
    subcategories: ["Hatha", "Vinyasa", "Ashtanga"],
  },
  {
    id: "5",
    name: "Meditation",
    icon: "meditation",
    iconSet: "MaterialCommunityIcons",
    subcategories: [],
  },
  {
    id: "6",
    name: "Nutrition",
    icon: "nutrition-outline",
    iconSet: "Ionicons",
    subcategories: [],
  },
  {
    id: "7",
    name: "Reiki",
    icon: "hand-right-outline",
    iconSet: "Ionicons",
    subcategories: [],
  },
  {
    id: "8",
    name: "Coaching",
    icon: "chatbubbles-outline",
    iconSet: "Ionicons",
    subcategories: [],
  },
  {
    id: "9",
    name: "Massages",
    icon: "spa-outline",
    iconSet: "MaterialCommunityIcons",
    subcategories: [],
  },
  {
    id: "10",
    name: "Acupunture",
    icon: "flask-outline",
    iconSet: "Ionicons",
    subcategories: [],
  },
  {
    id: "11",
    name: "Ayurveda",
    icon: "leaf-outline",
    iconSet: "Ionicons",
    subcategories: [],
  },
  {
    id: "12",
    name: "Cristal therapy",
    icon: "diamond-outline",
    iconSet: "Ionicons",
    subcategories: [],
  },
  {
    id: "13",
    name: "Naturopathy",
    icon: "nutrition-outline",
    iconSet: "Ionicons",
    subcategories: [],
  },
  {
    id: "14",
    name: "Homeopathy",
    icon: "medical-outline",
    iconSet: "Ionicons",
    subcategories: [],
  },
  {
    id: "15",
    name: "Chiropractic",
    icon: "body-outline",
    iconSet: "Ionicons",
    subcategories: [],
  },
    {
    id: "16",
    name: "Light Codes",
    icon: "sparkles-outline",
    iconSet: "Ionicons",
    subcategories: ["Light Code Embodiment", "Light Code Activation", "Light Transmission", "Light Code Integration"],
  },
  // TODO: Aggiungi altre categorie from API
];