import { ContactSocialMediaConfig } from '@/types/index';

export const contactsSocialMediaConfigurations: ContactSocialMediaConfig[] = [
  {
    id: 'website',
    propPath: 'contacts.website',
    iconName: 'globe-outline',
    iconSet: 'Ionicons',
    getDisplayValue: (val) => val,
    getUrl: (val) => val,
  },
  {
    id: 'email',
    propPath: 'contacts.email',
    iconName: 'mail-outline',
    iconSet: 'Ionicons',
    getDisplayValue: (val) => val,
    getUrl: (val) => `mailto:${val}`,
  },
  {
    id: 'phone',
    propPath: 'contacts.phone',
    iconName: 'call-outline',
    iconSet: 'Ionicons',
    getDisplayValue: (val) => val,
    getUrl: (val) => `tel:${val}`,
  },
  {
    id: 'whatsapp',
    propPath: 'contacts.whatsapp',
    iconName: 'logo-whatsapp',
    iconSet: 'Ionicons',
    getDisplayValue: (val) => val,
    getUrl: (val) => `whatsapp://send?phone=${val}`,
  },
  {
    id: 'telegram',
    propPath: 'contacts.telegram',
    iconName: 'paper-plane-outline', // o 'send' se preferisci MaterialCommunityIcons
    iconSet: 'Ionicons',
    getDisplayValue: (val) => val,
    getUrl: (val) => `tg://resolve?domain=${val}`,
  },
  {
    id: 'instagram',
    propPath: 'socialMedia.instagram',
    iconName: 'logo-instagram',
    iconSet: 'Ionicons',
    getDisplayValue: (val) => `${val}`,
    getUrl: (val) => `https://instagram.com/${val}`,
  },
  {
    id: 'facebook',
    propPath: 'socialMedia.facebook',
    iconName: 'logo-facebook',
    iconSet: 'Ionicons',
    getDisplayValue: (val) => `${val}`,
    getUrl: (val) => `https://facebook.com/${val}`,
  },
  {
    id: 'youtube',
    propPath: 'socialMedia.youtube',
    iconName: 'logo-youtube',
    iconSet: 'Ionicons',
    getDisplayValue: (val) => `${val}`,
    getUrl: (val) => `https://www.youtube.com/@${val}`, // Formato più comune per i canali YouTube con username
  },
  {
    id: 'tiktok',
    propPath: 'socialMedia.tiktok',
    iconName: 'logo-tiktok',
    iconSet: 'Ionicons',
    getDisplayValue: (val) => `${val}`,
    getUrl: (val) => `https://tiktok.com/@${val}`,
  },
  {
    id: 'pinterest',
    propPath: 'socialMedia.pinterest',
    iconName: 'logo-pinterest',
    iconSet: 'Ionicons',
    getDisplayValue: (val) => `${val}`,
    getUrl: (val) => `https://pinterest.com/${val}`,
  },
  {
    id: 'twitter',
    propPath: 'socialMedia.twitter',
    iconName: 'logo-twitter',
    iconSet: 'Ionicons',
    getDisplayValue: (val) => `${val}`,
    getUrl: (val) => `https://twitter.com/${val}`,
  },
  {
    id: 'linkedin',
    propPath: 'socialMedia.linkedin',
    iconName: 'logo-linkedin',
    iconSet: 'Ionicons',
    getDisplayValue: (val) => `${val}`,
    getUrl: (val) => `https://linkedin.com/in/${val}`,
  },
];